### ISSUE TITLE
Generates wrong Information

### ISSUE THREAD

**Issue by ghost** [ThisNils/exchange-code-generator#3]
Generates every code without any problem, but the exchange codes arent valid, could you please check on that?

**Comment by ThisNils** [comment]
What does "not valid" mean exactly? Are you aware that exchange codes expire after 300 seconds and can only be used once?

**Comment by ghost** [comment]
> What does "not valid" mean exactly? Are you aware that exchange codes expire after 300 seconds and can only be used once?

Well...

apparently iam too stupid to get my database encoding right....
Nvm. Ur Creator works like a charm (great job coding it).

at least thats ur first issue and it was user stupidity, keep up the great work :)
